[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.pdo",
  "php83Extensions.pdo_mysql",
  "php83Extensions.bcmath",
  "php83Extensions.zip",
  "php83Extensions.mbstring",
  "php83Extensions.pcntl",
  "php83Extensions.tokenizer",
  "php83Extensions.dom",
  "php83Extensions.xml",
  "php83Extensions.ctype",
  "php83Extensions.fileinfo",
  "php83Extensions.openssl",
  "php83Extensions.curl",
  "php83Packages.composer"
]

[phases.install]
cmds = [
  "mkdir -p bootstrap/cache storage/logs storage/framework/cache/data storage/framework/sessions storage/framework/views",
  "chmod -R 777 bootstrap storage",
  "composer install --no-dev --optimize-autoloader --no-interaction --no-scripts --ignore-platform-req=ext-oci8"
]

[phases.build]
cmds = []

[start]
cmd = "php artisan package:discover --ansi; ( php artisan migrate --force --no-interaction && php artisan db:seed --force --no-interaction ) & php artisan serve --host 0.0.0.0 --port ${PORT:-8080}"
